version: '3'
services:
  fastapi-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.fastapi-app
    networks:
      - kafka_tennisdatastreaming_kafka-network
    ports:
      - "8000:8000"

  tennis-simulator:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.tennis-simulator
    networks:
      - kafka_tennisdatastreaming_kafka-network

networks:
  kafka_tennisdatastreaming_kafka-network:
    external: true