FROM python:3.9

WORKDIR /app

# Install Python dependencies
COPY requirements/requirements.fastapi-app.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy Flask app and static files
COPY scripts/fastapi-app.py ./
COPY static/ ./static/
COPY templates/ ./templates/

EXPOSE 8000

# Start the FastAPI app using Uvicorn
CMD ["uvicorn", "fastapi-app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]